grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 4
    verbose: 2

model_selection:
  module_0:
    class: LinearRegression
    module: sklearn.linear_model
    params:
      fit_intercept: True
     
    search_param_grid:
      fit_intercept:
      - True
      - False

  module_1:
    class: RandomForestRegressor
    module: sklearn.ensemble
    params:
      n_estimators: 40
      min_samples_leaf: 2
    search_param_grid:
      n_estimators:
      - 100
      - 200
      max_depth:
      - 4
      - 5
      - 6

  module_2:
    class: XGBRegressor
    module: xgboost
    params:
      n_estimators: 100
      learning_rate: 0.1
    search_param_grid:
      n_estimators:
      - 100
      - 200
      learning_rate:
      - 0.1
      - 0.001
      - 0.05

