grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 4
    verbose: 2
model_selection:
  module_0:
    class: LinearRegression
    module: sklearn.linear_model
    params:
      fit_intercept: true
    search_param_grid:
      fit_intercept:
      - true
      - false
  module_1:
    class: RandomForestRegressor
    module: sklearn.ensemble
    params:
      min_samples_leaf: 5
      n_estimators: 500
      max_features: 21
      max_depth: 6
    search_param_grid:
      min_samples_leaf:
      - 4
      - 5
      n_estimators:
      - 100
      - 500
      max_features:
      - 12
      - 18
      - 21
      
